# Define the Problem

You are representing as a data analyst in the company CKL Ventures. Your client has provided you with a dataset containing sales data for various products over several years. You are required to perform data analysis, which includes data exploration, data manipulation, and data visualization. Apart from that, you need to provide insights and recommendations to improve sales and customer experience. The dataset includes the following attributes:
1. Product ID 
2. Name of Product
3. Category 
4. Discounted Price of the Product
5. Actual Price of the Product
6. Percentage of Discount for the Product
7. Rating of the Product
8. Number of people who voted for the Amazon rating

- The primary objective of analyzing the Amazon Sales Dataset is delve into product categories, prices, ratings, and sales patterns to identify characteristics that resonate with consumers and propel them to purchase

# 1. Importing Libraries

- Begin by importing libraries into your Jupyter Notebook
- Loading the dataset into your Jupyter Notebook.

In [1]:
#Begin by importing libraries into your Jupyter Notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Loading the dataset into your Jupyter Notebook
asales = pd.read_csv('amazon_sales.csv')

# 2. Overview of Data

- Examine the dataset by viewing at least 3 records from the top dataset and 5 records from the bottom of dataset.
- Check the data types for each of attribute.
- View the summary information for the dataset.

In [4]:
#Examine the dataset by viewing at least 3 records from the top dataset
asales.head(3)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...

In [5]:
#5 records from the bottom of dataset.
asales.tail()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [11]:
#view the summary information for the dataset.
asales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

# 3. Data Exploration

- Display the total attributes and records in the dataset.
- Examine and explore the unique values in the categorical data.
- Generate descriptive statistics for the DataFrame, including measures of central tendency and the shape of the distribution.
- Return the data types of each column in the DataFrame.
- Check for missing values in the 'rating_count' column and fill them with the median value.

In [8]:
#Display the total attributes and records in the dataset.
total_attributes, total_records = asales.shape
print("Total record (rows):",total_records )
print("Total attributes (cols):", total_attributes )

Total attributes (cols): 1465
Total records (rows): 16

In [10]:
#Examine and explore the unique values in the categorical data.

# Step1: Selecting only categorical columns
categorical_columns = asales.select_dtypes(include=['object']).columns

# Process to select each categorical column
for column in categorical_columns:
    unique_values = asales[column].unique()
    print("Unique values in column '{}':".format(column))
    print(unique_values)
    print("Total unique values:", len(unique_values))
    print("\n")

Unique values in column 'product_id':
['B07JW9H4J1' 'B098NS6PVG' 'B096MSW6CT' ... 'B009P2LIL4' 'B00J5DYCCA'
 'B01486F4G6']
Total unique values: 1351


Unique values in column 'product_name':
['Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)'
 'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)'
 'Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices'
 ...
 'Bajaj Majesty RX10 2000 Watts Heat Convector Room Heater (White, ISI Approved)'
 'Havells Ventil Air DSP 230mm Exhaust Fan (Pista Green)'
 'Borosil Jumbo 1000-Watt Grill Sandwich Maker (Black)']
Total unique values: 1337


Unique values in column 'category':
['Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions'
 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls'
 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions'
 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables'
 'Electronics|HomeTheater,TV&Video|Projectors'
 'Electronics|HomeAudio|Accessories|Adapters'
 'Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|DVICables'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables'
 'Electronics|HomeAudio|MediaStreamingDevices|StreamingClients'
 'Electronics|HomeTheater,TV&Video|AVReceivers&Amplifiers'
 'Electronics|HomeAudio|Speakers|TowerSpeakers'
 'Electronics|HomeTheater,TV&Video|Accessories|3DGlasses'
 'Electronics|WearableTechnology|SmartWatches'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Electronics|Accessories|MemoryCards|MicroSD'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|BasicMobiles'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers'
 'Electronics|Mobiles&Accessories|MobileAccessories|AutomobileAccessories|Cradles'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cables&Adapters|OTGAdapters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Tripods'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|SelfieSticks'
 'Electronics|Mobiles&Accessories|MobileAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor'
 'Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors'
 'Electronics|Mobiles&Accessories|MobileAccessories|StylusPens'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Bedstand&DeskMounts'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cases&Covers|BasicCases'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|HandlebarMounts'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CameraPrivacyCovers'
 'Electronics|Headphones,Earbuds&Accessories|Adapters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts'
 'Computers&Accessories|ExternalDevices&DataStorage|PenDrives'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Lapdesks'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|NotebookComputerStands'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboards'
 'MusicalInstruments|Microphones|Condenser'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|DisposableBatteries'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens'
 'Home&Kitchen|CraftMaterials|Scrapbooking|Tape'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MouseSets'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalHardDisks'
 'Electronics|Cameras&Photography|VideoCameras'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|Tabletop&TravelTripods'
 'OfficeProducts|OfficeElectronics|Calculators|Scientific'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|TripodLegs'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingMice'
 'Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|MousePads'
 'Computers&Accessories|Accessories&Peripherals|HardDiskBags'
 'Electronics|Cameras&Photography|Flashes|Macro&RinglightFlashes'
 'Computers&Accessories|NetworkingDevices'
 'Computers&Accessories|NetworkingDevices|Routers'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|Over-Ear'
 'Electronics|HomeAudio|Speakers|BluetoothSpeakers'
 'Electronics|GeneralPurposeBatteries&BatteryChargers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|RechargeableBatteries'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|BluetoothAdapters'
 'Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|CompleteTripodUnits'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|Notepads&MemoBooks'
 'Electronics|Cameras&Photography|Accessories|Film'
 'Computers&Accessories|Monitors'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps'
 'Electronics|Cameras&Photography|Accessories|Cleaners|CleaningKits'
 'Electronics|Cameras&Photography|SecurityCameras|DomeCameras'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|ScreenProtectors'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'OfficeProducts|OfficeElectronics|Calculators|Basic'
 'Computers&Accessories|Accessories&Peripherals|USBHubs'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Bags&Sleeves|LaptopSleeves&Slipcases'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalMemoryCardReaders'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|BottledInk'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|EthernetCables'
 'Computers&Accessories|Components|Memory'
 'Computers&Accessories|Accessories&Peripherals|UninterruptedPowerSupplies'
 'Electronics|Headphones,Earbuds&Accessories|Cases'
 'Electronics|Accessories|MemoryCards|SecureDigitalCards'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Flashes&SelfieLights|SelfieLights'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|Webcams&VoIPEquipment|Webcams'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CoolingPads'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Stands'
 'HomeImprovement|Electrical|Adapters&Multi-Outlets'
 'OfficeProducts|OfficePaperProducts|Paper|Copy&PrintingPaper|ColouredPaper'
 'Computers&Accessories|Components|InternalSolidStateDrives'
 'Electronics|HomeAudio|Speakers|MultimediaSpeakerSystems'
 'Computers&Accessories|NetworkingDevices|DataCards&Dongles'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers'
 'Electronics|Cameras&Photography|Accessories|Batteries&Chargers|BatteryChargers'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Bags,Cases&Sleeves|Cases'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pencils|WoodenPencils'
 'Computers&Accessories|Components|InternalHardDrives'
 'Computers&Accessories|Printers,Inks&Accessories|Printers'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pens'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|SATACables'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards'
 'Electronics|HomeAudio|Speakers|SoundbarSpeakers'
 'Electronics|Headphones,Earbuds&Accessories|Earpads'
 'Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters'
 'Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Headsets'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalSolidStateDrives'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkRefills&Kits'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries'
 'Electronics|Cameras&Photography|Accessories|PhotoStudio&Lighting|PhotoBackgroundAccessories|BackgroundSupports'
 'OfficeProducts|OfficeElectronics|Calculators|Financial&Business'
 'Electronics|PowerAccessories|SurgeProtectors'
 'Computers&Accessories|Tablets'
 'HomeImprovement|Electrical|CordManagement'
 'Home&Kitchen|CraftMaterials|PaintingMaterials'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|TonerCartridges'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens'
 'Computers&Accessories|Accessories&Peripherals|HardDriveAccessories|Caddies'
 'Computers&Accessories|Laptops|TraditionalLaptops'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|ElectricKettles'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|ElectricHeaters'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales'
 'Home&Kitchen|Kitchen&Dining|KitchenTools|ManualChoppers&Chippers|Choppers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|InductionCooktop'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|Kettle&ToasterSets'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|StorageWaterHeaters'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|ImmersionRods'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|JuicerMixerGrinders'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|EggBoilers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SandwichMakers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales|DigitalScales'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|VacuumSealers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|CanisterVacuums'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|PressureWashers,Steam&WindowCleaners'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HalogenHeaters'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Pop-upToasters'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HeatConvectors'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|ExhaustFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|DripCoffeeMachines'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterCartridges'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers'
 'Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|Wet-DryVacuums'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirPurifiers|HEPAAirPurifiers'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBags'
 'Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|IroningAccessories|SprayBottles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances'
 'Health&PersonalCare|HomeMedicalSupplies&Equipment|HealthMonitors|WeighingScales|DigitalBathroomScales'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|EspressoMachines'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|TableFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|MilkFrothers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Humidifiers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories|StandMixerAccessories'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|RoboticVacuums'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|YogurtMakers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers|ColdPressJuicers'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirConditioners|Split-SystemAirConditioners'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|StovetopEspressoPots'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags']
Total unique values: 211


Unique values in column 'discounted_price':
['₹399' '₹199' '₹329' '₹154' '₹149' '₹176.63' '₹229' '₹499' '₹299' '₹219'
 '₹350' '₹159' '₹349' '₹13,999' '₹249' '₹13,490' '₹970' '₹279' '₹59'
 '₹11,499' '₹14,999' '₹179' '₹389' '₹599' '₹99' '₹899' '₹32,999' '₹209'
 '₹19,999' '₹999' '₹333' '₹507' '₹309' '₹1,199' '₹799' '₹6,999' '₹230'
 '₹649' '₹15,999' '₹348' '₹32,990' '₹139' '₹263' '₹7,999' '₹1,599'
 '₹26,999' '₹115' '₹10,901' '₹1,434' '₹7,299' '₹325' '₹29,999' '₹27,999'
 '₹30,990' '₹269' '₹24,999' '₹18,990' '₹290' '₹345' '₹1,099' '₹719' '₹849'
 '₹21,999' '₹449' '₹37,999' '₹7,390' '₹273.10' '₹15,990' '₹210' '₹1,299'
 '₹347' '₹228' '₹1,499' '₹8,499' '₹20,990' '₹9,999' '₹489' '₹23,999'
 '₹689' '₹1,699' '₹655' '₹749' '₹195' '₹416' '₹368' '₹29,990' '₹339'
 '₹15,490' '₹9,490' '₹637' '₹1,089' '₹12,499' '₹1,399' '₹88' '₹57.89'
 '₹205' '₹949' '₹379' '₹8,990' '₹486' '₹5,699' '₹709' '₹47,990' '₹320'
 '₹129' '₹225' '₹547' '₹259' '₹239' '₹467' '₹11,990' '₹252' '₹204'
 '₹6,490' '₹235' '₹42,999' '₹173' '₹848.99' '₹1,249' '₹213' '₹598'
 '₹31,999' '₹128.31' '₹254' '₹89' '₹549' '₹77,990' '₹182' '₹96' '₹54,990'
 '₹439' '₹789' '₹790' '₹4,699' '₹18,999' '₹1,990' '₹2,299' '₹35,999'
 '₹8,999' '₹917' '₹45,999' '₹119' '₹21,990' '₹417.44' '₹215' '₹1,289'
 '₹609' '₹1,850' '₹13,990' '₹185' '₹218' '₹893' '₹10,990' '₹16,999' '₹699'
 '₹2,699' '₹246' '₹247' '₹1,369' '₹24,990' '₹61,999' '₹24,499' '₹10,499'
 '₹197' '₹1,519' '₹46,999' '₹1,799' '₹1,998' '₹1,999' '₹2,049' '₹6,499'
 '₹28,999' '₹569' '₹1,898' '₹9,499' '₹959' '₹1,149' '₹1,219' '₹18,499'
 '₹369' '₹12,999' '₹2,199' '₹16,499' '₹3,999' '₹2,998' '₹15,499' '₹873'
 '₹539' '₹1,075' '₹529' '₹4,790' '₹33,999' '₹10,999' '₹34,999' '₹2,999'
 '₹20,999' '₹22,999' '₹134' '₹7,499' '₹1,324' '₹12,490' '₹17,999' '₹2,099'
 '₹337' '₹251' '₹95' '₹4,499' '₹1,989' '₹4,999' '₹2,499' '₹79' '₹2,179'
 '₹44,999' '₹2,599' '₹2,799' '₹3,799' '₹281' '₹7,998' '₹120' '₹7,915'
 '₹1,055' '₹150' '₹474' '₹265' '₹37,990' '₹314' '₹365' '₹289' '₹217'
 '₹1,220' '₹475' '₹798' '₹266' '₹50' '₹130' '₹4,098' '₹519' '₹1,295'
 '₹1,889' '₹455' '₹1,059' '₹717' '₹39' '₹889' '₹191' '₹522' '₹681' '₹429'
 '₹100' '₹1,049' '₹656' '₹1,109' '₹169' '₹157' '₹479' '₹1,598' '₹294'
 '₹828' '₹745' '₹1,549' '₹1,469' '₹198' '₹12,000' '₹6,299' '₹571' '₹448'
 '₹579' '₹137' '₹1,495' '₹440' '₹1,329' '₹570' '₹1,529' '₹190' '₹729'
 '₹480' '₹238' '₹1,349' '₹1,792' '₹3,299' '₹125' '₹561' '₹5,599' '₹69'
 '₹478' '₹425' '₹378' '₹1,815' '₹67' '₹5,799' '₹4,449' '₹629' '₹2,595'
 '₹90' '₹1,345' '₹287' '₹879' '₹250' '₹469' '₹1,187' '₹328' '₹114'
 '₹1,490' '₹575' '₹178' '₹939' '₹1,439' '₹175' '₹3,303' '₹1,890' '₹310'
 '₹1,709' '₹2,025' '₹900' '₹2,490' '₹116' '₹200' '₹2,649' '₹596' '₹330'
 '₹1,234' '₹272' '₹3,498' '₹10,099' '₹397' '₹1,679' '₹354' '₹10,389'

In [12]:
#display the unique values for attribute 'product name'
asales['product_name'].unique()

array(['Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)',
       'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)',
       'Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices',
       ...,
       'Bajaj Majesty RX10 2000 Watts Heat Convector Room Heater (White, ISI Approved)',
       'Havells Ventil Air DSP 230mm Exhaust Fan (Pista Green)',
       'Borosil Jumbo 1000-Watt Grill Sandwich Maker (Black)'],
      dtype=object)

In [16]:
#Generate descriptive statistics for the DataFrame, including measures of central tendency and the shape of the distribution.
asales.describe()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
count,1465,1465,1465,1465,1465,1465,1465,1463,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,550,449,92,28,1143,1293,1194,1194,1194,1194,1212,1412,1465
top,B07JW9H4J1,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,50%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
freq,3,5,233,53,120,56,244,9,6,10,10,10,10,8,3,1

In [18]:
#Return the data types of each column in the DataFrame.
asales.dtypes

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

In [19]:
#check missing values in all attributes
missing_values_all = asales.isnull().sum()
print("Missing values for each attribute:")
print(missing_values_all)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1461,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1462,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1463,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1464,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
#Check for missing values in the 'rating_count' column and fill them with the median value.
missing_values = asales['rating_count'].isnull().sum()
print("Number of missing values in 'rating_count' column:", missing_values)

Number of missing values in 'rating_count' column: 2

In [24]:
#Remove commas from 'rating_count' column and convert to numeric
asales['rating_count'] = asales['rating_count']
.str.replace(',', '').astype(int)

#Fill missing values with the median value
median_rating_count = asales['rating_count'].median()
asales['rating_count'].fillna(median_rating_count, inplace=True)

In [25]:
#Verify that missing values have been filled
missing_values_after_fill = asales['rating_count'].isnull().sum()
print("Number of missing values in 'rating_count' column after filling:", missing_values_after_fill)

Number of missing values in 'rating_count' column after filling: 0

# 4. Data Manipulation

- Calculate the average discount percentage for all products.
- Identify the top 5 categories with the highest number of products.
- Convert the 'discounted_price' and 'actual_price' columns to numeric values and calculate the price difference for each product.
- Find out the number of unique users who have provided reviews.
- Create a new column 'review_length' containing the number of characters in each review.
- Sort the dataset based on the 'rating' column in descending order.
- Filter the dataset to include only products with a discount percentage greater than 20%.
- Calculate the total sales revenue generated from all products.
- Identify products with the highest and lowest ratings.
- Categorize products into different groups based on their product categories. What are the most popular sub-categories, and which ones have the highest average prices?
- Identify the best-selling products based on sales rank. Are there any trends or patterns?

# 5. Data Visualization

- Create a bar plot showing the distribution of products across different categories.
- Visualize the distribution of product ratings using a histogram.
- Create a pie chart to visualize the proportion of products with discounts greater than 20%.
- Create a line plot to visualize the trend of rating counts over time.
- Create a stacked bar plot to compare the proportion of products with different discount percentages across categories.
- Create a scatter plot to explore the relationship between the price of products and the number of products sold. Is there a pattern.
- Use Matplotlib or Seaborn to create a heat map showing the correlation between different numerical columns in the dataset.

# 6. Conclusion and Key Findings

Summarize your findings based on the analysis of the Amazon product sales dataset. What insights did you gain about the sales trends, popular categories, and customer preferences?
- How do the average discounted prices compare across different product categories?
- What is the relationship between rating and the number of reviews for each product?
- How does the discount percentage vary across different product categories?

#1. How do the average discounted prices compare across different product categories?
- Answer: To identify the average discounted price for each product category. Then, you can visualize this comparison using a bar plot or a box plot, where each category represents a bar or a box, and the height or the median of each bar/box represents the average discounted price for that category.

#2. Discounted prices have a significant impact on the sales revenue of products.
- To explore this relationship, we can create a scatter plot where the x-axis represents the number of reviews and the y-axis represents the rating. Each point on the plot represents a product, and the position of the point indicates both its rating and the number of reviews it has received. We can also calculate the correlation coefficient between the rating and the number of reviews to quantify the relationship.

#3. How does the discount percentage vary across different product categories?
- Answer: To analyze this variation, We can calculate summary statistics (such as mean, median, or distribution) of the discount percentage for each product category. Then, We also can visualize these comparisons using a box plot, where each box represents a product category and the distribution of discount percentages within that category. Additionally, you can use a bar plot to show the average discount percentage for each category.

Discuss on this:
- Products with higher ratings have a higher number of reviews.
- Discounted prices have a significant impact on the sales revenue of products.
- Certain product categories have higher average ratings compared to others.

1. **Products with higher ratings have a higher number of reviews:**
   - Findings: This analysis have give us the result which is higher rating have been influenced number of reviews. 
       - You may refer to visualization section.
   - Justification: When a product receives higher ratings, it often indicates higher customer satisfaction. Satisfied customers are more likely to leave positive reviews to express their satisfaction or share their positive experience with others. Therefore, products with higher ratings tend to attract more reviews. Additionally, popular products with higher ratings may also garner attention from more customers, leading to a higher number of reviews.

2. **Discounted prices have a significant impact on the sales revenue of products:**
   - Findings: The top products that are most frequently purchased by customers often have higher discount percentages. This is because they aim to attract more customers and encourage them to buy larger quantities instead of just one. As a result too, discounted products may experience increased sales volume, leading to higher overall sales revenue.
       - You may refer to Data Manipulation section.
   - Justification: Discounts are a common marketing strategy used to attract customers and drive sales. When prices are reduced through discounts, it often stimulates demand as customers perceive the product as offering greater value for money.  Additionally, discounts can also influence consumer behavior, encouraging impulse purchases or prompting customers to purchase larger quantities, further contributing to revenue generation.

3. **Certain product categories have higher average ratings compared to others:**
   - Findings: This is prove that the a good services or features provided to the customer will be increased sales volume and also rating. 
       - Product categories may vary in terms of the quality, features, and customer satisfaction associated with the products they offer. Some categories may inherently cater to products that are more likely to receive positive feedback due to their functionality, durability, or perceived value. 
       - you may refer to Data Manipulation and Data Visualization section.
   - Justification: For example, products in categories such as Electronics or Home Appliances might be subject to more stringent quality standards, resulting in higher average ratings.  Categories that offer products with limited functionality or lower perceived value may tend to have lower average ratings. Additionally, customer expectations and preferences within different categories can also influence the ratings received by products.

## END